### ISSUE TITLE
 error: offset for relative array access outside supported range

### ISSUE THREAD

**Issue by boris-741** [Krunklehorn/dead-by-default#1]
Got an error at start
Problem with light shader
____________

`Error: Cannot link shader program object:
Fragment info
-------------
Internal error: assembly compile error for fragment shader at offset 1981:
-- error message --
line 61, column 36:  error: invalid local parameter number
line 67, column 34:  error: out of bounds array access
line 72, column 21:  error: out of bounds array access
line 87, column 21:  error: out of bounds array access
line 92, column 31:  error: offset for relative array access outside supported range
line 93, column 31:  error: offset for relative array access outside supported range
line 94, column 31:  error: offset for relative array access outside supported range
line 95, column 29:  error: offset for relative array access outside supported range
line 96, column 29:  error: offset for relative array access outside supported range
line 97, column 33:  error: offset for relative array access outside supported range
line 105, column 30:  error: offset for relative array access outside supported range
line 111, column 21:  error: out of bounds array access
line 116, column 31:  error: offset for relative array access outside supported range
line 117, column 29:  error: offset for relative array access outside supported range
line 118, column 31:  error: offset for relative array access outside supported range
line 119, column 31:  error: offset for relative array access outside supported range
line 120, column 31:  error: offset for relative array access outside supported range
line 122, column 29:  error: offset for relative array access outside supported range
line 127, column 30:  error: offset for relative array access outside supported range
line 131, column 15:  error: out of bounds array access
line 137, column 21:  error: out of bounds array access
line 141, column 15:  error: out of bounds array access
line 145, column 23:  error: offset for relative array access outside supported range
line 148, column 23:  error: offset for relative array access outside supported range
line 151, column 23:  error: offset for relative array access outside supported range
line 187, column 21:  error: out of bounds array access
line 202, column 21:  error: out of bounds array access
line 207, column 36:  error: offset for relative array access outside supported range
line 208, column 31:  error: offset for relative array access outside supported range
line 209, column 31:  error: offset for relative array access outside supported range
line 210, column 29:  error: offset for relative array access outside supported range
line 211, column 29:  error: offset for relative array access outside supported range
line 212, column 33:  error: offset for relative array access outside supported range
line 220, column 30:  error: offset for relative array access outside supported range
line 226, column 21:  error: out of bounds array access
line 231, column 36:  error: offset for relative array access outside supported range
line 232, column 31:  error: offset for relative array access outside supported range
line 233, column 31:  error: offset for relative array access outside supported range
line 234, column 31:  error: offset for relative array access outside supported range
line 235, column 31:  error: offset for relative array access outside supported range
line 237, column 29:  error: offset for relative array access outside supported range
line 242, column 30:  error: offset for relative array access outside supported range
line 246, column 19:  error: out of bounds array access
line 284, column 21:  error: out of bounds array access
line 299, column 21:  error: out of bounds array access
line 304, column 36:  error: offset for relative array access outside supported range
line 305, column 31:  error: offset for relative array access outside supported range
line 306, column 31:  error: offset for relative array access outside supported range
line 307, column 29:  error: offset for relative array access outside supported range
line 308, column 29:  error: offset for relative array access outside supported range
line 309, column 33:  error: offset for relative array access outside supported range
line 317, column 30:  error: offset for relative array access outside supported range
line 323, column 21:  error: out of bounds array access
line 328, column 36:  error: offset for relative array access outside supported range
line 329, column 31:  error: offset for relative array access outside supported range
line 330, column 31:  error: offset for relative array access outside supported range
line 331, column 29:  error: offset for relative array access outside supported range
line 332, column 31:  error: offset for relative array access outside supported range
line 334, column 29:  error: offset for relative array access outside supported range
line 339, column 30:  error: offset for relative array access outside supported range
line 343, column 21:  error: out of bounds array access
line 349, column 15:  error: out of bounds array access
line 350, column 16:  error: out of bounds array access
line 354, column 15:  error: out of bounds array access
line 358, column 16:  error: out of bounds array access
line 382, column 15:  error: out of bounds array access
line 400, column 15:  error: out of bounds array access
-- internal assembly text --
!!NVfp4.0
OPTION NV_parameter_buffer_object2;
# cgc version 3.4.0001, build date Nov 14 2016
# command line args:
#vendor NVIDIA Corporation
#version 3.4.0.1
#profile gp4fp
#program main
#semantic ViewSpaceFromLocal
#semantic ClipSpaceFromView
#semantic ClipSpaceFromLocal
#semantic ViewNormalFromLocal
#semantic love_ScreenSize
#semantic love_VideoYChannel
#semantic love_VideoCbChannel
#semantic love_VideoCrChannel
#semantic MainTex
#semantic LINE_WIDTH
#semantic LUMINANCE
#semantic VISIBILITY
#semantic DEBUG_CLIPPING
#semantic scale
#semantic circles
#semantic boxes
#semantic lines
#semantic lights
#semantic nCircles
#semantic nBoxes
#semantic nLines
#semantic nLights
#var float4 gl_FragCoord : $vin.WPOS : WPOS : -1 : 1
#var float4 love_PixelColor : $vout.COL0 : COL0[0] : -1 : 1
#var float4x4 ViewSpaceFromLocal :  : , 4 : -1 : 0
#var float4x4 ClipSpaceFromView :  : , 4 : -1 : 0
#var float4x4 ClipSpaceFromLocal :  : , 4 : -1 : 0
#var float3x3 ViewNormalFromLocal :  : , 3 : -1 : 0
#var float4 love_ScreenSize :  : c[1009] : -1 : 1
#var sampler2D love_VideoYChannel :  :  : -1 : 0
#var sampler2D love_VideoCbChannel :  :  : -1 : 0
#var sampler2D love_VideoCrChannel :  :  : -1 : 0
#var sampler2D MainTex :  :  : -1 : 0
#var float4 VaryingTexCoord :  :  : -1 : 0
#var float4 VaryingColor :  :  : -1 : 0
#var float LINE_WIDTH :  : c[1010] : -1 : 1
#var bool LUMINANCE :  : c[1011] : -1 : 1
#var bool VISIBILITY :  :  : -1 : 0
#var bool DEBUG_CLIPPING :  : c[1012] : -1 : 1
#var float scale :  : c[1013] : -1 : 1
#var float4 circles[0] :  : c[0] : -1 : 1
#var float4 boxes[0] :  : c[197] : -1 : 1
#var float4 lines[0] :  : c[591] : -1 : 1
#var float4 lights[0] :  : c[985] : -1 : 1
#var int nCircles :  : c[1014] : -1 : 1
#var int nBoxes :  : c[1015] : -1 : 1
#var int nLines :  : c[1016] : -1 : 1
#var int nLights :  : c[1017] : -1 : 1
#default LINE_WIDTH = 1
#default LUMINANCE = 1
#default VISIBILITY = 1
#default DEBUG_CLIPPING = 0
PARAM c[1018] = { program.local[0..1017] };
TEMP R0, R1, R2, R3, R4, R5, R6, R7, R8;
TEMP RC, HC;
OUTPUT result_color0 = result.color;
MOV.F R0, {0, 0, 0, 0}.x;
MOV.F R5.x, fragment.position;
MAD.F R5.y, fragment.position, c[1009].z, c[1009].w;
MOV.U R5.z, {1, 0, 0, 0}.x;
MOV.F R4.x, {100000, 0, 0, 0};
MOV.S R2.z, {0, 0, 0, 0}.x;
REP.S ;
SLT.S R2.x, R2.z, c[1014];
SEQ.U R2.x, -R2, {0, 0, 0, 0};
MOV.U.CC RC.x, -R2;
BRK   (GT.x);
MOV.U R2.w, R2.z;
ADD.F R2.xy, R5, -c[R2.w];
DP2.F R2.x, R2, R2;
RSQ.F R2.x, R2.x;
RCP.F R2.x, R2.x;
ADD.F R2.x, R2, -c[R2.w].z;
MIN.F R4.x, R4, R2;
ADD.S R2.z, R2, {1, 0, 0, 0}.x;
ENDREP;
MOV.S R4.y, {0, 0, 0, 0}.x;
REP.S ;
SLT.S R2.x, R4.y, c[1015];
SEQ.U R2.x, -R2, {0, 0, 0, 0};
MOV.U.CC RC.x, -R2;
BRK   (GT.x);
MOV.U R4.z, R4.y;
ADD.F R2.xy, R5, -c[R4.z + 197];
MUL.F R2.w, R2.x, c[R4.z + 198].y;
MUL.F R2.z, R2.y, c[R4.z + 198].y;
MAD.F R2.y, R2, c[R4.z + 198].x, R2.w;
MAD.F R2.x, R2, c[R4.z + 198], -R2.z;
ADD.F R2.xy, |R2|, -c[R4.z + 197].zwzw;
MAX.F R2.zw, R2.xyxy, {0, 0, 0, 0}.x;
MAX.F R2.y, R2.x, R2;
DP2.F R2.z, R2.zwzw, R2.zwzw;
RSQ.F R2.x, R2.z;
MIN.F R2.y, R2, {0, 0, 0, 0}.x;
RCP.F R2.x, R2.x;
ADD.F R2.x, R2, R2.y;
ADD.F R2.x, R2, -c[R4.z + 198].z;
MIN.F R4.x, R4, R2;
ADD.S R4.y, R4, {2, 0, 0, 0}.x;
ENDREP;
MOV.S R2.z, {0, 0, 0, 0}.x;
REP.S ;
SLT.S R2.x, R2.z, c[1016];
SEQ.U R2.x, -R2, {0, 0, 0, 0};
MOV.U.CC RC.x, -R2;
BRK   (GT.x);
MOV.U R2.w, R2.z;
ADD.F R2.xy, R5, -c[R2.w + 591];
MUL.F R4.y, R2, c[R2.w + 591].w;
MAD.F R4.y, R2.x, c[R2.w + 591].z, -R4;
MUL.F R4.w, R2.x, c[R2.w + 591];
MIN.F R4.z, R4.y, c[R2.w + 592].x;
MAX.F R2.x, R4.z, {0, 0, 0, 0};
MAD.F R2.y, R2, c[R2.w + 591].z, R4.w;
ADD.F R2.x, R4.y, -R2;
DP2.F R2.x, R2, R2;
RSQ.F R2.x, R2.x;
RCP.F R2.x, R2.x;
ADD.F R2.x, R2, -c[R2.w + 592].y;
MIN.F R4.x, R4, R2;
ADD.S R2.z, R2, {2, 0, 0, 0}.x;
ENDREP;
ADD.F R2.x, c[1010], {0.5, 0, 0, 0};
SGE.F R2.x, R4, -R2;
TRUNC.U.CC HC.x, R2;
IF    NE.x;
MOV.S R5.w, {0, 0, 0, 0}.x;
REP.S ;
SLT.S R2.x, R5.w, c[1017];
SEQ.U R2.x, -R2, {0, 0, 0, 0};
MOV.U.CC RC.x, -R2;
BRK   (GT.x);
SNE.U R2.x, c[1011], {0, 0, 0, 0};
MOV.U.CC RC.x, -R2;
IF    NE.x;
MOV.U R2.x, R5.w;
MOV.F R2, c[R2.x + 986];
ELSE;
MOV.U R2.x, R5.w;
MUL.F R2, c[R2.x + 986], c[R2.x + 986].w;
ENDIF;
MOV.U R4.x, R5.w;
MOV.F R4, c[R4.x + 985];
ADD.F R4.xy, R4, -R5;
DP2.F R6.x, R4, R4;
RSQ.F R6.x, R6.x;
RCP.F R6.x, R6.x;
SGT.F R6.z, R6.x, R4;
MOV.F R6.y, R4.w;
TRUNC.U.CC HC.x, R6.z;
MOV.U R4.w, {1, 0, 0, 0}.x;
IF    NE.x;
MOV.F R1, {0, 0, 0, 0}.x;
MOV.U R4.w, {0, 0, 0, 0}.x;
ENDIF;
MOV.U.CC RC.x, R4.w;
IF    NE.x;
ADD.F R6.z, R4, -R6.x;
SLT.F R6.w, R6.x, {1, 0, 0, 0}.x;
TRUNC.U.CC HC.x, R6.w;
DIV.F R6.z, R6, R4.z;
IF    NE.x;
MOV.F R1, R2;
MOV.U R4.w, {0, 0, 0, 0}.x;
ENDIF;
MOV.U.CC RC.x, R4.w;
IF    NE.x;
DP2.F R1.x, R4, R4;
RSQ.F R1.x, R1.x;
MUL.F R1.xy, R1.x, R4;
MUL.F R6.w, R6.y, R6.x;
MOV.F R7.y, {0.0099999998, 0, 0, 0}.x;
MOV.F R7.x, R6;
REP.S {64, 0, 0, 0};
MAD.F R1.zw, R1.xyxy, R7.y, R5.xyxy;
MOV.F R7.z, {100000, 0, 0, 0}.x;
MOV.S R4.z, {0, 0, 0, 0}.x;
REP.S ;
SLT.S R4.x, R4.z, c[1014];
SEQ.U R4.x, -R4, {0, 0, 0, 0};
MOV.U.CC RC.x, -R4;
BRK   (GT.x);
MOV.U R4.w, R4.z;
ADD.F R4.xy, R1.zwzw, -c[R4.w];
DP2.F R4.x, R4, R4;
RSQ.F R4.x, R4.x;
RCP.F R4.x, R4.x;
ADD.F R4.x, R4, -c[R4.w].z;
MIN.F R7.z, R7, R4.x;
ADD.S R4.z, R4, {1, 0, 0, 0}.x;
ENDREP;
MOV.S R7.w, {0, 0, 0, 0}.x;
REP.S ;
SLT.S R4.x, R7.w, c[1015];
SEQ.U R4.x, -R4, {0, 0, 0, 0};
MOV.U.CC RC.x, -R4;
BRK   (GT.x);
MOV.U R8.x, R7.w;
ADD.F R4.xy, R1.zwzw, -c[R8.x + 197];
MUL.F R4.w, R4.x, c[R8.x + 198].y;
MUL.F R4.z, R4.y, c[R8.x + 198].y;
MAD.F R4.y, R4, c[R8.x + 198].x, R4.w;
MAD.F R4.x, R4, c[R8.x + 198], -R4.z;
ADD.F R4.xy, |R4|, -c[R8.x + 197].zwzw;
MAX.F R4.zw, R4.xyxy, {0, 0, 0, 0}.x;
MAX.F R4.y, R4.x, R4;
DP2.F R4.z, R4.zwzw, R4.zwzw;
RSQ.F R4.x, R4.z;
MIN.F R4.y, R4, {0, 0, 0, 0}.x;
RCP.F R4.x, R4.x;
ADD.F R4.x, R4, R4.y;
ADD.F R4.x, R4, -c[R8.x + 198].z;
MIN.F R7.z, R7, R4.x;
ADD.S R7.w, R7, {2, 0, 0, 0}.x;
ENDREP;
MOV.S R4.z, {0, 0, 0, 0}.x;
REP.S ;
SLT.S R4.x, R4.z, c[1016];
SEQ.U R4.x, -R4, {0, 0, 0, 0};
MOV.U.CC RC.x, -R4;
BRK   (GT.x);
MOV.U R4.w, R4.z;
ADD.F R4.xy, R1.zwzw, -c[R4.w + 591];
MUL.F R7.w, R4.y, c[R4.w + 591];
MAD.F R7.w, R4.x, c[R4.w + 591].z, -R7;
MUL.F R8.y, R4.x, c[R4.w + 591].w;
MIN.F R8.x, R7.w, c[R4.w + 592];
MAX.F R4.x, R8, {0, 0, 0, 0};
MAD.F R4.y, R4, c[R4.w + 591].z, R8;
ADD.F R4.x, R7.w, -R4;
DP2.F R4.x, R4, R4;
RSQ.F R4.x, R4.x;
RCP.F R4.x, R4.x;
ADD.F R4.x, R4, -c[R4.w + 592].y;
MIN.F R7.z, R7, R4.x;
ADD.S R4.z, R4, {2, 0, 0, 0}.x;
ENDREP;
ADD.F R1.z, R7, c[1010].x;
ADD.F R1.z, R1, {0.5, 0, 0, 0}.x;
SLT.F R1.w, R1.z, -R6.y;
TRUNC.U.CC HC.x, R1.w;
IF    NE.x;
MOV.U.CC RC.x, {1, 0, 0, 0};
MOV.F R6.w, {0, 0, 0, 0}.x;
BRK   (GT.x);
ENDIF;
DIV.F R1.w, R1.z, R7.y;
SLT.F R4.x, R1.w, R6.w;
TRUNC.U.CC HC.x, R4;
IF    NE.x;
MUL.F R4.x, R6.y, {2, 0, 0, 0};
SLE.F R4.x, R1.z, R4;
TRUNC.U.CC HC.x, R4;
MOV.F R6.w, R1;
IF    NE.x;
MOV.F R7.x, R7.y;
ENDIF;
ENDIF;
MAX.F R1.z, |R1|, {1, 0, 0, 0}.x;
ADD.F R7.y, R7, R1.z;
SGT.F R1.z, R7.y, R6.x;
TRUNC.U.CC HC.x, R1.z;
IF    NE.x;
MOV.U.CC RC.x, {1, 0, 0, 0};
BRK   (GT.x);
ENDIF;
ENDREP;
SLT.F R1.z, R7.x, R6.x;
TRUNC.U.CC HC.x, R1.z;
IF    NE.x;
REP.S {8, 0, 0, 0};
MAD.F R1.zw, R1.xyxy, R7.x, R5.xyxy;
MOV.F R7.y, {100000, 0, 0, 0}.x;
MOV.S R4.z, {0, 0, 0, 0}.x;
REP.S ;
SLT.S R4.x, R4.z, c[1014];
SEQ.U R4.x, -R4, {0, 0, 0, 0};
MOV.U.CC RC.x, -R4;
BRK   (GT.x);
MOV.U R4.w, R4.z;
ADD.F R4.xy, R1.zwzw, -c[R4.w];
DP2.F R4.x, R4, R4;
RSQ.F R4.x, R4.x;
RCP.F R4.x, R4.x;
ADD.F R4.x, R4, -c[R4.w].z;
MIN.F R7.y, R7, R4.x;
ADD.S R4.z, R4, {1, 0, 0, 0}.x;
ENDREP;
MOV.S R7.z, {0, 0, 0, 0}.x;
REP.S ;
SLT.S R4.x, R7.z, c[1015];
SEQ.U R4.x, -R4, {0, 0, 0, 0};
MOV.U.CC RC.x, -R4;
BRK   (GT.x);
MOV.U R7.w, R7.z;
ADD.F R4.xy, R1.zwzw, -c[R7.w + 197];
MUL.F R4.w, R4.x, c[R7.w + 198].y;
MUL.F R4.z, R4.y, c[R7.w + 198].y;
MAD.F R4.y, R4, c[R7.w + 198].x, R4.w;
MAD.F R4.x, R4, c[R7.w + 198], -R4.z;
ADD.F R4.xy, |R4|, -c[R7.w + 197].zwzw;
MAX.F R4.zw, R4.xyxy, {0, 0, 0, 0}.x;
MAX.F R4.y, R4.x, R4;
DP2.F R4.z, R4.zwzw, R4.zwzw;
RSQ.F R4.x, R4.z;
MIN.F R4.y, R4, {0, 0, 0, 0}.x;
RCP.F R4.x, R4.x;
ADD.F R4.x, R4, R4.y;
ADD.F R4.x, R4, -c[R7.w + 198].z;
MIN.F R7.y, R7, R4.x;
ADD.S R7.z, R7, {2, 0, 0, 0}.x;
ENDREP;
MOV.S R4.z, {0, 0, 0, 0}.x;
REP.S ;
SLT.S R4.x, R4.z, c[1016];
SEQ.U R4.x, -R4, {0, 0, 0, 0};
MOV.U.CC RC.x, -R4;
BRK   (GT.x);
MOV.U R4.w, R4.z;
ADD.F R4.xy, R1.zwzw, -c[R4.w + 591];
MUL.F R7.z, R4.y, c[R4.w + 591].w;
MAD.F R7.z, R4.x, c[R4.w + 591], -R7;
MUL.F R8.x, R4, c[R4.w + 591].w;
MIN.F R7.w, R7.z, c[R4.w + 592].x;
MAX.F R4.x, R7.w, {0, 0, 0, 0};
MAD.F R4.y, R4, c[R4.w + 591].z, R8.x;
ADD.F R4.x, R7.z, -R4;
DP2.F R4.x, R4, R4;
RSQ.F R4.x, R4.x;
RCP.F R4.x, R4.x;
ADD.F R4.x, R4, -c[R4.w + 592].y;
MIN.F R7.y, R7, R4.x;
ADD.S R4.z, R4, {2, 0, 0, 0}.x;
ENDREP;
ADD.F R1.z, R7.y, c[1010].x;
MAD.F R1.z, -R6.y, {2, 0, 0, 0}.x, R1;
ADD.F R1.z, R1, R7.x;
ADD.F R7.x, R1.z, {0.5, 0, 0, 0};
ENDREP;
ENDIF;
MAD.F R1.y, c[1013].x, {32, 0, 0, 0}.x, R6;
MAD.F R1.z, -c[1013].x, {16, 0, 0, 0}.x, R1.y;
ADD.F R1.x, R6, -R7;
MUL.F R1.y, R1.x, R1;
RCP.F R1.w, R1.z;
MAD.F R4.x, c[1013], {32, 0, 0, 0}, -R6.y;
MUL.F R1.x, R1, R4;
MAD.F R1.w, -R1.y, R1, R6.x;
DIV.F R1.z, R1.y, R1.z;
MAD.F R4.x, -c[1013], {16, 0, 0, 0}, R4;
RCP.F R1.y, R4.x;
MAD.F R1.y, R1.x, R1, -R1.z;
DIV.F.SAT R1.y, R1.w, R1.y;
MUL.F R1.z, R1.y, R1.y;
MAD.F R1.y, -R1, {2, 3, 0, 0}.x, {2, 3, 0, 0};
ADD.F R1.x, R6, R6.y;
MUL.F R1.x, R6.w, R1;
DIV.F R1.x, R1, R6.y;
MUL.F R1.z, R1, R1.y;
MUL.F.SAT R1.x, R1, {0.5, 0, 0, 0};
MAD.F R1.y, -R1.x, {2, 3, 0, 0}.x, {2, 3, 0, 0};
MUL.F R1.x, R1, R1;
MUL.F R1.x, R1, R1.y;
MAD.F R1.y, -R1.x, R1.z, R1.z;
ADD.F R1.x, R1, R1.y;
MUL.F R4.x, R6.z, R6.z;
MUL.F R1, R2, R1.x;
MUL.F R1, R1, R4.x;
ENDIF;
ENDIF;
ADD.F R0, R0, R1;
ADD.S R5.w, R5, {2, 0, 0, 0}.x;
ENDREP;
SNE.U R1.x, c[1011], {0, 0, 0, 0};
MOV.U.CC RC.x, -R1;
IF    NE.x;
MUL.F R1.x, R0.y, {0.71520001, 0, 0, 0};
MUL.F R1.y, R0.z, {0.0722, 0, 0, 0}.x;
MAD.F R1.x, R0, {0.21259999, 0, 0, 0}, R1;
SNE.F R1.z, R1.x, -R1.y;
TRUNC.U.CC HC.x, R1.z;
ADD.F R1.x, R1, R1.y;
IF    NE.x;
MUL.F R0.xyz, R0, R0.w;
DIV.F R0.xyz, R0, R1.x;
MUL.F R0.xyz, R0, {0.0722, 0, 0, 0}.x;
MOV.F R0.w, {1, 0, 0, 0}.x;
ELSE;
MOV.F R0, {0, 0, 0, 0}.x;
ENDIF;
ENDIF;
SNE.U R1.x, c[1012], {0, 0, 0, 0};
MOV.U.CC RC.x, -R1;
IF    NE.x;
SGE.F R1.x, R0.z, {1, 0, 0, 0};
TRUNC.U R1.z, R1.x;
SGE.F R1.y, R0, {1, 0, 0, 0}.x;
SGE.F R1.x, R0, {1, 0, 0, 0};
TRUNC.U R1.y, R1;
TRUNC.U R1.x, R1;
AND.U R1.x, R1, R1.y;
AND.U.CC HC.x, R1, R1.z;
IF    NE.x;
MUL.F R1.y, R5, {0.1, 0, 0, 0}.x;
MUL.F R1.x, R5, {0.1, 0, 0, 0};
FLR.F R1.y, R1;
FLR.F R1.x, R1;
ADD.F R1.x, R1, R1.y;
MUL.F R1.y, R1.x, {0.5, 0, 0, 0}.x;
FLR.F R1.y, R1;
MAD.F R3.xyz, -R1.y, {2, 0, 0, 0}.x, R1.x;
MOV.F R3.w, {1, 0, 0, 0}.x;
MOV.U R5.z, {0, 0, 0, 0}.x;
ELSE;
SGE.F R1.x, R0, {1, 0, 0, 0};
TRUNC.U.CC HC.x, R1;
IF    NE.x;
MOV.F R3, {1, 0, 0, 0}.xyxx;
MOV.U R5.z, {0, 0, 0, 0}.x;
ELSE;
SGE.F R1.x, R0.y, {1, 0, 0, 0};
TRUNC.U.CC HC.x, R1;
IF    NE.x;
MOV.F R3, {1, 0, 0, 0}.xxyx;
MOV.U R5.z, {0, 0, 0, 0}.x;
ELSE;
SGE.F R1.x, R0.z, {1, 0, 0, 0};
TRUNC.U.CC HC.x, R1;
IF    NE.x;
MOV.F R3, {0, 1, 0, 0}.xyyy;
MOV.U R5.z, {0, 0, 0, 0}.x;
ENDIF;
ENDIF;
ENDIF;
ENDIF;
ENDIF;
ENDIF;
MOV.U.CC RC.x, R5.z;
IF    NE.x;
MOV.F R3, R0;
ENDIF;
MOV.F result_color0, R3;
END
# 386 instructions, 9 R-regs

stack traceback:
        [string "boot.lua"]:777: in function <[string "boot.lua"]:773>
        [C]: in function 'newShader'
        singletons/stache.lua:105: in function 'load'
        main.lua:10: in function 'load'
        main.lua:22: in function <main.lua:18>
        [C]: in function 'xpcall'
        [string "boot.lua"]:793: in function <[string "boot.lua"]:780>
        [C]: in function 'xpcall'
`

**Comment by Krunklehorn** [comment]
```
getRendererInfo() -----------------------------------------------------------------------------
OpenGL  3.3.0   NVIDIA Corporation      GeForce GTS 250/PCIe/SSE2

getCanvasFormats() -----------------------------------------------------------------------------
depth32fstencil8                true
r32f                            true
r16f                            true
rg32f                           true
rgba32f                         true
rgba8                           true
rgb565                          true
normal                          true
srgba8                          true
rgb5a1                          true
depth24stencil8                 true
hdr                             true
rgba16                          false
rgb10a2                         true
r16                             false
rgba4                           true
r8                              true
stencil8                        true
rg16                            false
rg16f                           true
depth16                         true
depth32f                        true
la8                             false
depth24                         true
rg8                             true
rg11b10f                        true
rgba16f                         true

getSupported() -----------------------------------------------------------------------------
pixelshaderhighp                true
glsl3                           true
lighten                         true
multicanvasformats              true
clampzero                       true
shaderderivatives               true
instancing                      true
fullnpot                        true

getSystemLimits() -----------------------------------------------------------------------------
texturesize                     8192
pointsize                       189.875
canvasmsaa                      16
cubetexturesize                 8192
anisotropy                      16
texturelayers                   512
multicanvas                     8
volumetexturesize               2048

getTextureTypes() -----------------------------------------------------------------------------
2d                              true
volume                          true
array                           true
cube                            true
```
This was your debug output...

Nothing seemed too far off from my own system. You can try reducing SDF_MAX_BRUSHES in light.frag, shape.frag and constants.lua to something like 100 or even 25. See if that helps?

**Comment by boris-741** [comment]
I reduce value to 25
It's helped
thank.

**Comment by Krunklehorn** [comment]
Cool! Glad it worked. That constant is currently setup to push the number of available uniform registers as high as it can go. Unfortunately that's a hardware and implementation dependent constant that I don't have a way to query an upper bound for at the moment.

Guess I'll just have to set it to something more conservative in the future.
